{% set name = "mastercard-oauth1-signer" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mastercard-oauth1-signer-{{ version }}.tar.gz
  sha256: 1ba92ec570e76bfc2bde18f5a50321a025b6b9ade32cf929f44ab31f644f563d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests
    - pyopenssl >=22.1.0,<=23.2.0
    - urllib3
    # Includes all secure packages
    - deprecated

test:
  imports:
    - oauth1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Mastercard/oauth1-signer-python
  summary: Mastercard OAuth1 Signer.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
