{% set name = "mastercard-oauth1-signer" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mastercard-oauth1-signer-{{ version }}.tar.gz
  sha256: bfbefe17969e4518ebf8a9d0acbfd09e11d5766f0e8f24c5ec557ea93b4c83e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - cryptography >=42.0.0
    - python >={{ python_min }}
    - requests
    - urllib3
    # Includes all secure packages
    - deprecated

test:
  imports:
    - oauth1
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Mastercard/oauth1-signer-python
  summary: Mastercard OAuth1 Signer.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
